name: scrapy-amac
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.2
  - attrs==19.3.0
  - automat==20.2.0
  - cffi==1.14.0
  - constantly==15.1.0
  - cssselect==1.1.0
  - fake-useragent==0.1.11
  - hyperlink==19.0.0
  - idna==2.9
  - incremental==17.5.0
  - lxml==4.5.0
  - parsel==1.5.2
  - protego==0.1.16
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pycparser==2.20
  - pydispatcher==2.0.5
  - pyhamcrest==2.0.2
  - pyopenssl==19.1.0
  - queuelib==1.5.0
  - scrapy==2.0.1
  - six==1.14.0
  - twisted==20.3.0
  - w3lib==1.21.0
  - zope.interface==5.1.0
  - pip:
      - cryptography==2.9
      - service-identity==18.1.0
